# 워크플로우 이름 설정
name: CICD Github Action

# 시작 조건
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정

    # 환경 변수 설정 (GitHub Secrets에서 불러오기)
    env:
      RDSHOSTNAME: ${{ secrets.RDSHOSTNAME }}
      RDSNAME: ${{ secrets.RDSNAME }}
      RDSUSERNAME: ${{ secrets.RDSUSERNAME }}
      RDSPASSWORD: ${{ secrets.RDSPASSWORD }}
      RDSPORT: ${{ secrets.RDSPORT }}

    # 실행 스텝 지정
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 백엔드 프로젝트 빌드 (프론트 파일은 이미 resource/static에 있음)
      - name: Build with Gradle (Skip Tests)
        run: ./gradlew clean build -x test

      # 빌드된 JAR 파일 확인
      - name: List generated files
        run: ls -al ./build/libs

      - name: Set artifact
        run: |
          echo "artifact=$(find ./build/libs -name '*SNAPSHOT.jar')" >> $GITHUB_ENV

      # Elastic Beanstalk 배포
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:        
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         application_name: bookdochilsung
         environment_name: bookdochilsung-env
         version_label: github-action-${{ github.sha }}
         region: ap-northeast-2
         deployment_package: ${{ env.artifact }}
